# Generated by Django 5.2.6 on 2026-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0003_entry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='day_quality',
            field=models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very good')], default=4),
            preserve_default=False,
        ),
    ]
