# Generated by Django 5.2.6 on 2026-01-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0004_entry_day_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='day_quality',
            new_name='quality',
        ),
    ]
