# Generated by Django 5.2.6 on 2026-01-22 13:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0005_rename_day_quality_entry_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('mood', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Very Good')])),
                ('energy', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('stress', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('day_rating', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')])),
                ('reflection', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
