# Generated by Django 5.2.6 on 2026-01-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0006_dailycheckin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckin',
            name='day_rating',
        ),
    ]
