# Generated by Django 5.2.6 on 2026-01-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0007_remove_dailycheckin_day_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckin',
            name='reflection',
        ),
    ]
