# Generated by Django 5.2.6 on 2026-01-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0008_remove_dailycheckin_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='activity',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Light'), (3, 'Intense')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='sleep',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Okay'), (3, 'Good')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='social',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Some'), (3, 'A lot')], default=2),
            preserve_default=False,
        ),
    ]
