# Generated by Django 5.2.6 on 2026-02-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0009_dailycheckin_activity_dailycheckin_sleep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='activity',
            field=models.IntegerField(choices=[(1, 'Not at all'), (2, 'A little'), (3, 'Some'), (4, 'Quite a bit'), (5, 'A lot')]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='energy',
            field=models.IntegerField(choices=[(1, 'Very low'), (2, 'Low'), (3, 'Okay'), (4, 'Good'), (5, 'Very good')]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='sleep',
            field=models.IntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Okay'), (4, 'Good'), (5, 'Great')]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='social',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Some'), (3, 'A few'), (4, 'A lot'), (5, 'Very social day')]),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='stress',
            field=models.IntegerField(choices=[(1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very high')]),
        ),
    ]
